### ISSUE TITLE
Feature Request: pdf_split() function appending too many zeros into file name.

### ISSUE THREAD

**Issue by nikhil-nikss** [ropensci/qpdf#3]
Hi,

While working on pdf_split to split my pdf file into seperate pages it creates a file name and append zeros with the length of pdf into file name.e.g if my pdf file consists of 16 pages then it appends 16 zeros to file name which works fine for small pdf file but in my scenerio my pdf file is of 25k pages so in this case it tries to append 25k zeros to my file name which in turns break my code and not able to create seperate file.So requesting to please modify and add features to remove zeros or allow to set custom file name.
Will appreciate your all efforts.
Thanks :)

**Comment by nikhil-nikss** [comment]
Worked perfectly with other function from the same package.

**Comment by Dasonk** [comment]
https://stackoverflow.com/questions/55534032/file-name-containing-zeros-as-same-as-file-length

is what they're referring to.  I still think a change could be made to pdf_split to get this to work though.
